<?php 
$wo['have_stories'] = false;
$user_stories = $db->where('user_id', $wo['user']['user_id'])->get(T_USER_STORY,null,array('id'));
if (!empty($user_stories)) {
    $wo['have_stories'] = true;
    $wo['story_seen_class'] = 'seen_story';

    foreach ($user_stories as $key => $value) {
        $is_seen = $db->where('story_id',$value->id)->where('user_id',$wo['user']['user_id'])->getValue(T_STORY_SEEN,'COUNT(*)');

        if ($is_seen == 0) {
            $wo['story_seen_class'] = 'unseen_story';
        }
    }
}
 ?>
<div class="sidebar-conatnier">
    <div class="col-md-3 sidebar rightcol">
        <div class="home profile-style main sidebar-profile-style">
            <div class="card hovercard">
                <div class="cardheader">
                    <img src="<?php echo $wo['user']['cover']?>" id="cover-image" alt="<?php echo $wo['user']['name']?> Cover Image">
                </div>
                <div class="avatar">
                    <img id="updateImage-<?php echo $wo['user']['user_id']?>" alt="<?php echo $wo['user']['name']?> Profile Picture" src="<?php echo $wo['user']['avatar']?>" <?php if ($wo['have_stories'] == true) { ?> class="<?php echo($wo['story_seen_class']); ?> see_all_stories" data_story_user_id="<?php echo $wo['user']['user_id']?>"  data_story_type="user" <?php } ?>>
                </div>
                <div class="info">
                    <div class="title">
                        <a id="user-full-name" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username'];?>" href="<?php echo $wo['user']['url'];?>"><?php echo $wo['user']['name']?></a>
                        <?php if($wo['user']['verified'] == 1):?>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="verified-color feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>" data-toggle="tooltip"><path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" /></svg>
                        <?php endif;?>
						<p>@<?php echo $wo['user']['username']?></p>
                    </div>
                </div>
            </div>
        </div>
        
	  
        <?php 
        if ($wo['config']['pages'] == 1) {
        $promoted_page = Wo_GetPromotedPage();
        if (count($promoted_page) > 0) { ?>
        <?php } } ?>
        <?php

        $birth = Wo_CheckBirthdays();
        if (count($birth) > 0) { ?>
        <ul class="list-group">
            <li class="list-group-item text-muted sidebar-title-back" contenteditable="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #e91e63;"><path d="M12.89 1.45l8 4A2 2 0 0 1 22 7.24v9.53a2 2 0 0 1-1.11 1.79l-8 4a2 2 0 0 1-1.79 0l-8-4a2 2 0 0 1-1.1-1.8V7.24a2 2 0 0 1 1.11-1.79l8-4a2 2 0 0 1 1.78 0z"></path><polyline points="2.32 6.16 12 11 21.68 6.16"></polyline><line x1="12" y1="22.76" x2="12" y2="11"></line></svg> <?php echo $wo['lang']['friends_birthdays'];?>
            </li>
            <div class="sidebar-users-may-know-containerr">
                <?php 
                    foreach ($birth as $wo['UsersList']) {
                        $wo['UsersList']['user_name'] = mb_substr($wo['UsersList']['name'],0,10, "utf-8");
                        echo Wo_LoadPage('sidebar/sidebar-birthday-list');
                    } 
                    ?>
            </div>
            <div class="clear"></div>
        </ul>
        <?php 
            }
            $users = Wo_UserSug(4);
            if (count($users) != 0) {
            ?>
        <?php
            }
            if ($wo['config']['pages'] == 1) {
            $pages = Wo_PageSug(1);
            if (count($pages) != 0) {
            ?>
        <ul class="list-group" id="sidebar-page-list-container">
            <li class="list-group-item text-muted sidebar-title-back" contenteditable="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #673AB7;"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"></path><line x1="4" y1="22" x2="4" y2="15"></line></svg> <?php echo $wo['lang']['pages_you_may_like']; ?>
                <span onclick="Wo_ReloadSideBarPages();" class="<?php echo Wo_RightToLeft('pull-right');?> refresh">
                <i class="fa fa-repeat progress-icon" data-icon="repeat"></i>
                </span>
            </li>
            <li>
                <div class="sidebar-pages-may-know-container">
                    <?php 
                        foreach ($pages as $wo['PageList']) {
                            $wo['PageList']['user_name'] = $wo['PageList']['name'];
                            echo Wo_LoadPage('sidebar/sidebar-home-page-list');
                        } 
                        ?>
                </div>
                <div class="clear"></div>
            </li>
        </ul>
        <?php } }  ?>
        <?php
        if ($wo['config']['groups'] == 1) {
            $groups = Wo_GroupSug(5);
            if (count($groups) > 0) {
            ?>
        <ul class="list-group" id="sidebar-group-list-container">
            <li class="list-group-item text-muted sidebar-title-back" contenteditable="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #e91e63;"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg> <?php echo $wo['lang']['suggested_groups'];?> <span onclick="Wo_ReloadSideBarGroups();" class="<?php echo Wo_RightToLeft('pull-right');?>  refresh">
                <i class="fa fa-repeat progress-icon" data-icon="repeat"></i>
                </span>
            </li>
            <li>
                <div class="sidebar-group-may-know-container">
                    <?php 
                        foreach ($groups as $wo['GroupList']) {
                            $wo['GroupList']['name'] = mb_substr($wo['GroupList']['name'],0,20, "utf-8");
                            echo Wo_LoadPage('sidebar/sidebar-group-list');
                        } 
                        ?>
                </div>
                <div class="clear"></div>
            </li>
        </ul>
        <?php } } ?>
        <ul class="list-group">
            <li class="list-group-item sidebar-title-back" contenteditable="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #795548;"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg> <?php echo $wo['lang']['invite_your_frineds_home']; ?></li>
            <li>
                <form action="#" method="post" class="row invite-user-form">
					<div class="invite-user-form-alert"></div>
					<div class="invite-user-combine">
                    <input type="text" name="email" placeholder="<?php echo $wo['lang']['email']; ?>" class="form-control">
                    <button class="btn btn-main btn-sm" title="<?php echo $wo['lang']['send_invitation']; ?>">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>
					</button>
					</div>
                    <div class="clear"></div>
                </form>
            </li>
        </ul>
        <?php if ($wo['config']['user_ads'] == 1): ?>
        <?php endif; ?>
        <?php echo Wo_LoadPage('footer/sidebar-footer')?>
    </div>
</div>

<script>
    function Wo_GetNewActivities() {
      var before_activity_id = $('#activities-wrapper > .activity').attr('data-activity-id');
      if (typeof before_activity_id === 'undefined') {
           return false;
      }
      $.post(Wo_Ajax_Requests_File() + '?f=activities&s=get_new_activities', {
        before_activity_id: before_activity_id
      }, function (data) {
        if(data.status == 200) {
          $('.activities-wrapper').prepend(data.html);
        }
      });
    }
    function Wo_GetMoreActivities() {
      var activity_container = $('.activity-container');
      var after_activity_id = $('#activities-wrapper .activity:last').attr('data-activity-id');
      Wo_progressIconLoader(activity_container);
      $.post(Wo_Ajax_Requests_File() + '?f=activities&s=get_more_activities', {
        after_activity_id: after_activity_id
      }, function (data) {
        if(data.status == 200) {
          if(data.html.length == 0) {
            $('.no-activities').html(data.message);
          } else {
            $('#activities-wrapper').append(data.html);
          }
          $("#activities-wrapper").animate({
            scrollTop: $('#activities-wrapper')[0].scrollHeight
          }, 100);
          Wo_progressIconLoader(activity_container);
        }
      });
    }
   $(function() {
     $('form.invite-user-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=invite_user',
       beforeSend: function() {
         Wo_progressIconLoader($('form.invite-user-form').find('button'));
       },
       success: function(data) {
         if (data.status == 200) {
            $('.invite-user-form-alert').html('<div class="alert alert-success">' + data.message + '</div>');
            $('.alert-success').fadeIn(300);
         } else {
             var errors = data.errors.join("<br>");
             $('.invite-user-form-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         Wo_progressIconLoader($('form.invite-user-form').find('button'));
       }
     });
   });
 
var userStep = 170;
var userScrolling = false;

// Wire up events for the 'scrollUp' link:
$("#scrollRight").bind("click", function(event) {
    event.preventDefault();
    $(".sidebar-product-slider").animate({
        scrollLeft: "-=" + userStep + "px"
    });
});

$("#scrollLeft").bind("click", function(event) {
    event.preventDefault();
    $(".sidebar-product-slider").animate({
        scrollLeft: "+=" + userStep + "px"
    });
});

function scrollContent(direction) {
    var amount = (direction === "right" ? "-=1px" : "+=1px");
    $(".sidebar-product-slider").animate({
        scrollLeft: amount
    }, 1, function() {
        if (userScrolling) {
            scrollContent(direction);
        }
    });
}

$(document).ready(function(){
  $('.wo_pro_users').slick({
	  centerMode: true,
	  centerPadding: '1px',
	  slidesToShow: 3,
	  autoplay: true,
	  autoplaySpeed: 2000,
	  arrows: false,
	  speed: 900,
	  <?php if($wo['language_type'] == 'rtl') { ?>
  rtl: true,
  <?php } ?>
	  responsive: [
    {
      breakpoint: 992,
      settings: {
        arrows: false,
        centerMode: true,
        centerPadding: '40px',
        slidesToShow: 5
      }
    },
	{
      breakpoint: 768,
      settings: {
        arrows: false,
        centerMode: true,
        centerPadding: '40px',
        slidesToShow: 4
      }
    },
	{
      breakpoint: 520,
      settings: {
        arrows: false,
        centerMode: true,
        centerPadding: '40px',
        slidesToShow: 3
      }
    },
    {
      breakpoint: 420,
      settings: {
        arrows: false,
        centerMode: true,
        centerPadding: '40px',
        slidesToShow: 2
      }
    },
	{
      breakpoint: 340,
      settings: {
        arrows: false,
        centerMode: true,
        centerPadding: '40px',
        slidesToShow: 1
      }
    }
  ]
  });
});
</script>