<?php if ($wo['loggedin'] == true && Wo_IsMobile() == false) { ?>
<div class="left-sidebar">
	<ul>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=saved-posts');?>" data-ajax="?link1=saved-posts">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#673ab7;"><path d="M4 3h16a2 2 0 0 1 2 2v6a10 10 0 0 1-10 10A10 10 0 0 1 2 11V5a2 2 0 0 1 2-2z"></path><polyline points="8 10 12 14 16 10"></polyline></svg>
				<?php echo $wo['lang']['saved_posts'];?>
			</a>
		</li>
		<?php if ($wo['config']['groups'] == 1) { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=groups'); ?>" data-ajax="?link1=groups">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#03A9F4;"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg>
				<?php echo $wo['lang']['my_groups'];?>
			</a>
		</li>
		<?php } ?>
		<li><hr></li>
		<?php if ($wo['config']['blogs'] == 1) { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=blogs'); ?>">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#f35d4d;"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>
				<?php echo $wo['lang']['blog'] ?>
			</a>
		</li>
		<?php } ?>
		<?php if (Wo_CanBlog() == true) { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=my-blogs'); ?>" data-ajax="?link1=my-blogs">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#009da0;"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path></svg>
				<?php echo $wo['lang']['my_articles'] ?>
			</a>
		</li>
		<?php } ?>
        <?php if ($wo['config']['events'] == 1) { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=events'); ?>" data-ajax="?link1=events">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#f25e4e;"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
				<?php echo $wo['lang']['events'] ?>
			</a>
		</li>
		<?php } ?>
		<?php if ($wo['config']['forum'] == 1) { ?>
		<li><hr></li>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=forum'); ?>" data-ajax="?link1=forum">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#e91e63;"><circle cx="12" cy="12" r="2"></circle><path d="M16.24 7.76a6 6 0 0 1 0 8.49m-8.48-.01a6 6 0 0 1 0-8.49m11.31-2.82a10 10 0 0 1 0 14.14m-14.14 0a10 10 0 0 1 0-14.14"></path></svg>
				<?php echo $wo['lang']['forum'];?>
			</a>
		</li>
		<?php } ?>
		<?php if ($wo['config']['find_friends'] == 1) { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=friends-nearby'); ?>">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#b2c17c;"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
				<?php echo $wo['lang']['find_friends'];?>
			</a>
		</li>
		<?php } ?>
	</ul>
</div>
<?php } ?>